version: "3"
services:
  reverse_proxy:
    image: nginx:1.23.0-alpine
    restart: always
    volumes:
      - ./frontend/local_reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: 1
    ports:
      - "3000:3000"
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: development
      args:
        NEXT_PUBLIC_PLATFORM_URL: ${NEXT_PUBLIC_PLATFORM_URL}
        API_KEY: ${API_KEY}
        TENANT_ID: ${TENANT_ID}
    volumes:
      - ./frontend/src:/app/frontend/src
    restart: always
    env_file: .env
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:3001
    depends_on:
      - backend


  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: development
    volumes:
      - ./backend/src:/app/backend/src
    restart: always
    env_file: .env
    environment:
      DATABASE_URL: postgres://roqone:roqone@db:5432/roqone_dev
      MAX_GRAPHQL_QUERY_DEPTH: 20
    depends_on:
      - db
    ports:
      - "3001:3001"
      - "9229:9229"

  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: roqone
      POSTGRES_PASSWORD: roqone
      POSTGRES_DB: roqone_dev
      PGUSER: roqone
      PGDATABASE: roqone_dev
    ports:
      - "5432:5432"
